### PR TITLE
Added cookie stealing

### PR DESCRIPTION
**Pull request by quickdaffy**
Added cookie stealing. That's about it

### CODE REVIEW

**Review by addi00000 — COMMENTED** [review]
The cookie logging I had implemented before was practically the same as this. The reason I removed that one an will not merge this one is because they both run into decode errors on edge (at least for me) and lead to an exception being thrown that kills the process.

**Comment by quickdaffy** [comment]
You should be able to, if I didn’t add it then it was an oversight.

**Comment by addi00000** [comment]
The problem is it cant decrypt the cookie unless its an isolated issue
Ill add  try except clause as a temporary fix when I have the chance

**Comment by addi00000** [comment]
https://github.com/addi00000/empyrean/commit/024833c28a86011d91b8cc6ae363380826389301

**Pull request closed without merging**
